import time
time.sleep(2)
nome = input ('Qual é o seu  ')
time.sleep(1)
print("")
print ('Responda as proximas perguntas só com numeros.')
time.sleep(1)
print ('')
print ('Diga sua data de nascimento.')
print ('')
idadedia = input ('Que dia você nasceu? ') 
idademes = input ('que mês você nasceu? ')
idadeano = input ('Que ano você nasceu? ')
time.sleep(1)
print ('')
print ('Diga a data atual.')
print ('')
dia = input ('Dia: ') 
mes = input ('Mês: ')
ano = input ('Ano: ')
time.sleep(1)
print ('')
print ('Digite: "começar" para começar a falar com o robo.')
print ('')   
go = input ('Digite oque foi dito: ')
if go == ('começar'):
    print ('Bom dia', nome, 'Voce nasceu no dia:', idadedia, 'de:', idademes, 'no ano de:', idadeano, )
    time.sleep(1)
    print ('')
    print ('Estamos na data de:', dia, mes, ano,)
    print ('')
    print ('')
else: print ('você escreveu errado.')
